### ISSUE TITLE
Error during installation: No matching version found for @dessert-box/core@^0.2.0 inside the workspace

### ISSUE THREAD

**Issue by talovski** [TheMightyPenguin/dessert-box#28]
When trying to install the package using npm or pnpm (haven't tried yarn) I get the following error:

```
In : No matching version found for @dessert-box/core@^0.2.0 inside the workspace
This error happened while installing the dependencies of @dessert-box/react@0.6.0
Progress: resolved 29, reused 19, downloaded 0, added 0
```

I think it's connected to the monorepo setup, but not sure what is the problem exactly and how to resolve it locally without cloning the whole dessert-box repo.

**Comment by MMMikeM** [comment]
Seeing the same issue inside a regular repo, using pnpm, with the core package installed. Wondering if it's related to [this](https://github.com/TheMightyPenguin/dessert-box/blob/0d0af7d109217b28082aa06c7e9b27263cd18f13/packages/react/package.json#L37)?

**Comment by brandonpittman** [comment]
Can't install this either. 😢

**Comment by brandonpittman** [comment]
Not sure, but could it be that the publish wasn't run with `pnpm publish` and the dependencies weren't swapped for the proper syntax?

https://pnpm.io/workspaces#publishing-workspace-packages

**Comment by brandonpittman** [comment]
Pulled repo and tried `npm pack` and `pnpm pack` on the `react` package.

If you use `pnpm pack` the dependency is correctly swapped out. I have to imagine they used `npm publish` and it pushed a broken `package.json` to NPM.

**Comment by brandonpittman** [comment]
I think a re-publish using pnpm would solve this.

**Comment by TheMightyPenguin** [comment]
@talovski @MMMikeM @brandonpittman just fixed this, sorry about this issue, somehow pinned the wrong version when publishing, will add a few tests so this does not happen again!!

Just published 0.7.0 which should be working!!

**Comment by TheMightyPenguin** [comment]
@brandonpittman excited to know you want to try the styled utility! let me know how it works for you!

**Comment by brandonpittman** [comment]
@TheMightyPenguin 

Install worked fine, but getting an error when trying to use `styled`.

@see: https://github.com/TheMightyPenguin/dessert-box/issues/30
