### ISSUE TITLE
Support for React.Component argument to styled

### ISSUE THREAD

**Issue by brettinternet** [TheMightyPenguin/dessert-box#32]
Would it be possible to support passing a React component to `styled` like so?

```ts
type Props = { className?: string }

const Component: React.FC<Props> = ({ className }) => <div className={className}>...</div>

const StyledComponent = styled(Component, { background: 'blue' })
````

**Comment by TheMightyPenguin** [comment]
Hey @brettinternet I don't think this will be possible, as the argument for functions made with [`addFunctionSerializer`](https://vanilla-extract-css.netlify.app/documentation/api/add-function-serializer/) need to be serializable and components are not :( As we use this function internally, this is a technical limitation
